name: Multi stage docker build
on:
  push:
    brach: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/multistage-app .
      - name: push image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/multistage-app
      - name: Run container
        run: docker run myapp
